kind: pipeline  
type: docker  
name: default  
  
  
steps:  
- name: test-build  
  image: node 
  commands:
    - npm install -g pnpm
    - pnpm get registry 
    - pnpm config set registry https://registry.npmmirror.com/
    - pnpm install  
    # - npm run test  
    - pnpm build 
  volumes:  
  - name: dist  
    path: /drone/src/dist  
  
- name: deploy  
  image: appleboy/drone-scp  
  settings:  
    host: 39.108.180.7
    port: 22  
    username: root  
    key:  
      from_secret: ssh_key  
    target: /var/www/web  
    source: /drone/src/dist  
    rm: false 
  when:  
    branch: [ main ]  
    event: [ push ]  
 
trigger:  
  branch:  
    - main  
  event:  
    - push