kind: pipeline  
type: docker  
name: default  
  
  
steps:  
- name: test-build  
  image: node  
  commands:
    - npm install -g pnpm
    - pnpm install  
    # - npm run test  
    - pnpm build 
    - pwd                     # 打印当前工作目录  
    - ls -lha /drone/src/    # 列出/drone/src/下的内容  
    # - ls -lha /drone/src/frontend/  # 列出frontend目录内容

    - ls -l /drone/src/dist  # 列出dist目录内容  
  volumes:  
  - name: dist  
    path: /drone/src/dist  
  
- name: deploy  
  image: appleboy/drone-scp  
  settings:  
    host: 39.108.180.7
    port: 22  
    username: root  
    key:  
      from_secret: ssh_key  
    target: /var/www/web  
    source: /drone/src/dist  
    rm: false 
  when:  
    branch: [ main ]  
    event: [ push ]  
 
trigger:  
  branch:  
    - main  
  event:  
    - push